# Generated by Django 4.0.4 on 2022-09-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
    ]
