# Generated by Django 4.0.4 on 2022-09-18 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='selled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('img', models.URLField(max_length=300)),
                ('salle_price', models.IntegerField()),
                ('tolisting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
