# Generated by Django 4.0.4 on 2022-09-18 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_selled'),
    ]

    operations = [
        migrations.AddField(
            model_name='selled',
            name='salles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
