# Generated by Django 4.0.4 on 2022-09-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_selled_salles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selled',
            name='tolisting',
        ),
    ]
