# Generated by Django 4.0.4 on 2022-09-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_selled_tolisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='chk',
            field=models.UUIDField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
