# Generated by Django 4.0.4 on 2022-09-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment_chk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='chk',
            field=models.UUIDField(),
        ),
    ]
