# Generated by Django 4.0.4 on 2022-09-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_comment_chk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='chk',
            field=models.CharField(max_length=200),
        ),
    ]
